name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2"

dependencies:
  flutter:
    sdk: flutter

  animated_text_kit: ^2.0.0

  cupertino_icons: ^0.1.2

  firebase_core: ^0.4.3+2

  firebase_auth: ^0.15.3+1

  cloud_firestore: ^0.13.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/
